[package]
name = "smlogic"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"
egui = { version = "0.31", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
